site_name: micah takes photographs
site_address: http://www.micahrich.com/blog
site_description: images and thoughts from micah's everyday life
author: micah rich
author_link: http://www.micahrich.com
